// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class LoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void login() {
    // Test name: AldisLogin.Login
    // Step # | name | target | value
    // 1 | open | https://shop.aldi.us/ | 
    // Open the window https://shop.aldi.us/
    driver.get("https://shop.aldi.us/");
    // 2 | setWindowSize | 606x809 | 
    // Resize the window
    driver.manage().window().setSize(new Dimension(606, 809));
    // 3 | click | xpath=(//a[contains(text(),'Log In')])[2] | 
    // Click on the login button
    driver.findElement(By.xpath("(//a[contains(text(),\'Log In\')])[2]")).click();
    // 4 | click | name=email | 
    // Click on the email entry form
    driver.findElement(By.name("email")).click();
    // 5 | type | name=email | nwhitemizzou@gmail.com
    // Type in the login email address
    driver.findElement(By.name("email")).sendKeys("nwhitemizzou@gmail.com");
    // 6 | click | name=password | 
    // Click on the password entry form
    driver.findElement(By.name("password")).click();
    // 7 | type | name=password | 4ZTLn.xP24SXpUz
    // Type in the password
    driver.findElement(By.name("password")).sendKeys("4ZTLn.xP24SXpUz");
    // 8 | click | xpath=//span[contains(.,'Log in')] | 
    // AldisLogin.Login to the site
    driver.findElement(By.xpath("//span[contains(.,\'Log in\')]")).click();
  }
}
