// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class LogoutTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void logout() {
    // Test name: logout.Logout
    // Step # | name | target | value
    // 1 | open | https://shop.aldi.us/store/aldi/storefront | 
    driver.get("https://shop.aldi.us/store/aldi/storefront");
    // 5 | click | css=.css-1i3qizy > svg | 
    driver.findElement(By.cssSelector(".css-1i3qizy > svg")).click();
    // 7 | click | css=li:nth-child(11) .css-1ebckir-MenuLink | 
    driver.findElement(By.cssSelector("li:nth-child(11) .css-1ebckir-MenuLink")).click();
    // 8 | assertConfirmation | Are you sure you want to log out? | 
    assertThat(driver.switchTo().alert().getText(), is("Are you sure you want to log out?"));
    // 9 | webdriverChooseOkOnVisibleConfirmation |  | 
    driver.switchTo().alert().accept();
    // 10 | close |  | 
    driver.close();
  }
}
